### ISSUE TITLE
[Not Work] Debian 10

### ISSUE THREAD

**Issue by itsdan25** [TandelK/Get5-AutoInstallScript#31]
Installing MySQL Server
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package mysql-server is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'mysql-server' has no installation candidate
Failed to start mysql.service: Unit mysql.service not found.

**Comment by TandelK** [comment]
Debian 10 uses mariadb for which you can modify the script to install mariadb server and restart mariadb services. Or esle install mysql using repo system using this link [https://www.digitalocean.com/community/tutorials/how-to-install-the-latest-mysql-on-debian-10](https://www.digitalocean.com/community/tutorials/how-to-install-the-latest-mysql-on-debian-10)

**Comment by TandelK** [comment]
@itsdan25 I am closing this issue as there has been no follow up. The current script i would recommend using on Ubuntu 16.04 ,18.04 and for Debian builds i would recommend changing a code on your own if you  like to maintain a repo 

Debian 8 - https://tecadmin.net/install-mysql-debian-8-jessie/
Debian 10 link i have given above or else use mariadb server .
