### ISSUE TITLE
Include character utf8mb4 mysql database encoding

### ISSUE THREAD

**Issue by xe1os** [TandelK/Get5-AutoInstallScript#5]
Include/Enable utf8mb4 character in the script to allow updation of stats for players having utf character nickname.

Reference - https://github.com/splewis/get5-web/issues/101

**Comment by TandelK** [comment]
Sure will look into this

**Comment by TandelK** [comment]
Well its already there from starting you can check it at https://github.com/TandelK/Get5-AutoInstallScript/blob/4651a739ef2c5c3d31812ead479c39fe0b029adf/get5_auto_installer.sh#L248

**Comment by TandelK** [comment]
Do you want me to add function in script that can modify existing database to new collation
