### ISSUE TITLE
[BUG] Auto-Script not complete

### ISSUE THREAD

**Issue by xe1os** [TandelK/Get5-AutoInstallScript#7]
**Describe the bug**
Doesn't ask or perform database migrations

**To Reproduce**
1. Run ./get5_auto_installer.sh
2. select 1) install
3. select branch 2)development
4. after creating apache config file it ends.

**Expected behavior**
Post all downloads & configurations it should do database migrations.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04 LTS

**Comment by TandelK** [comment]
Sorry didnt look at this coming. Will do the script re-work once again for that step.

**Comment by TandelK** [comment]
I literally forgot to do the main command.

**Comment by xe1os** [comment]
@TandelK getting error while trying to open web panel after the script completion.

http://prnt.sc/ouhf05

**Comment by TandelK** [comment]
Need to fix and check each and every section of script what might be causing this issue. Most probably due to old update of prod_config file

**Comment by xe1os** [comment]
> Need to fix and check each and every section of script what might be causing this issue. Most probably due to old update of prod_config file

Suggestion -

It would be better if you add `cp prod_config.py.default prod_config.py` and replace $get5dbpass, $steamapi, $secretkey, $dbkey, $adminsteamid using sed or something else in the script for generating the latest prod_config file instead of below insertions.



`echo "##### You must change these before running" >> /var/www/get5-web/instance/prod_config.py
			echo "SQLALCHEMY_DATABASE_URI = 'mysql://get5:$get5dbpass@localhost/get5'  # Sqlalchemy database connection info" >> /var/www/get5-web/instance/prod_config.py
			echo "STEAM_API_KEY = '$steamapi'  # See https://steamcommunity.com/dev/apikey" >> /var/www/get5-web/instance/prod_config.py
			echo "SECRET_KEY = '$secretkey'  # Secret key used for flask cookies" >> /var/www/get5-web/instance/prod_config.py
			echo "DATABASE_KEY = '$dbkey'  # Used for encryption on database. MUST BE 16 BYTES." >> /var/www/get5-web/instance/prod_config.py
			echo "WEBPANEL_NAME = 'Get5' # Used for the title header on the webpage." >> /var/www/get5-web/instance/prod_config.py
			echo "" >> /var/www/get5-web/instance/prod_config.py
			echo "##### Everything below this line is optional to change" >> /var/www/get5-web/instance/prod_config.py
			echo "" >> /var/www/get5-web/instance/prod_config.py
			echo "import os" >> /var/www/get5-web/instance/prod_config.py
			echo "" >> /var/www/get5-web/instance/prod_config.py
			echo "location = os.path.realpath(os.path.join(os.getcwd(), os.path.dirname(__file__), '..', 'logs'))" >> /var/www/get5-web/instance/prod_config.py
			echo "LOG_PATH = os.path.join(location, 'get5.log')" >> /var/www/get5-web/instance/prod_config.py
			echo "" >> /var/www/get5-web/instance/prod_config.py
			echo "DEBUG = False" >> /var/www/get5-web/instance/prod_config.py
			echo "TESTING = False" >> /var/www/get5-web/instance/prod_config.py
			echo "" >> /var/www/get5-web/instance/prod_config.py
			echo "SQLALCHEMY_TRACK_MODIFICATIONS = False" >> /var/www/get5-web/instance/prod_config.py
			echo "USER_MAX_SERVERS = 10  # Max servers a user can create" >> /var/www/get5-web/instance/prod_config.py
			echo "USER_MAX_TEAMS = 100  # Max teams a user can create" >> /var/www/get5-web/instance/prod_config.py
			echo "USER_MAX_MATCHES = 1000  # Max matches a user can create" >> /var/www/get5-web/instance/prod_config.py
			echo "USER_MAX_SEASONS = 100 # Max seasons a user can create" >> /var/www/get5-web/instance/prod_config.py
			echo "DEFAULT_PAGE = '/matches'" >> /var/www/get5-web/instance/prod_config.py
			echo "ADMINS_ACCESS_ALL_MATCHES = False  # Whether admins can always access any match admin panel" >> /var/www/get5-web/instance/prod_config.py
			echo "CREATE_MATCH_TITLE_TEXT = False # Whether settings for 'match title text' and 'team text' appear on 'create a match page'" >> /var/www/get5-web/instance/prod_config.py
			echo "" >> /var/www/get5-web/instance/prod_config.py
			echo "# All maps that are selectable in the 'create a match' page" >> /var/www/get5-web/instance/prod_config.py
			echo "MAPLIST = [" >> /var/www/get5-web/instance/prod_config.py
			echo "	'de_dust2'," >> /var/www/get5-web/instance/prod_config.py
			echo "	'de_inferno'," >> /var/www/get5-web/instance/prod_config.py
			echo "	'de_mirage'," >> /var/www/get5-web/instance/prod_config.py
			echo "	'de_nuke'," >> /var/www/get5-web/instance/prod_config.py
			echo "	'de_overpass'," >> /var/www/get5-web/instance/prod_config.py
			echo "	'de_train'," >> /var/www/get5-web/instance/prod_config.py
			echo "	'de_vertigo'," >> /var/www/get5-web/instance/prod_config.py
			echo "	'de_season'," >> /var/www/get5-web/instance/prod_config.py
			echo "	'de_cbble'," >> /var/www/get5-web/instance/prod_config.py
			echo "	'de_cache'," >> /var/www/get5-web/instance/prod_config.py
			echo "]" >> /var/www/get5-web/instance/prod_config.py
			echo "" >> /var/www/get5-web/instance/prod_config.py
			echo "# Maps whose checkbox is selected (in the mappool) by default in the 'create a match' page" >> /var/www/get5-web/instance/prod_config.py
			echo "DEFAULT_MAPLIST = [" >> /var/www/get5-web/instance/prod_config.py
			echo "	'de_dust2'," >> /var/www/get5-web/instance/prod_config.py
			echo "	'de_inferno'," >> /var/www/get5-web/instance/prod_config.py
			echo "	'de_mirage'," >> /var/www/get5-web/instance/prod_config.py
			echo "	'de_nuke'," >> /var/www/get5-web/instance/prod_config.py
			echo "	'de_overpass'," >> /var/www/get5-web/instance/prod_config.py
			echo "	'de_train'," >> /var/www/get5-web/instance/prod_config.py
			echo "	'de_vertigo'," >> /var/www/get5-web/instance/prod_config.py
			echo "]" >> /var/www/get5-web/instance/prod_config.py
			echo "" >> /var/www/get5-web/instance/prod_config.py
			echo "# You may set the server to allow allow whitelisted steamids to login." >> /var/www/get5-web/instance/prod_config.py
			echo "# By default any user can login and create teams/servers/matches." >> /var/www/get5-web/instance/prod_config.py
			echo "WHITELISTED_IDS = ['$adminsteamid']" >> /var/www/get5-web/instance/prod_config.py
			echo "" >> /var/www/get5-web/instance/prod_config.py
			echo "# Admins will have extra access to create 'public' teams, and if ADMINS_ACCESS_ALL_MATCHES" >> /var/www/get5-web/instance/prod_config.py
			echo "# is set, they can access admin info for all matches (can pause, cancel, etc.) ANY match." >> /var/www/get5-web/instance/prod_config.py
			echo "ADMIN_IDS = ['$adminsteamid']" >> /var/www/get5-web/instance/prod_config.py`

**Comment by xe1os** [comment]
@TandelK have a look at my fork

**Comment by TandelK** [comment]
Can you send me Pull request ?

**Comment by TandelK** [comment]
Add me in Discord also. Need to discuss about it https://discord.gg/dgzUzSB

**Comment by TandelK** [comment]
@xe1os i think so we have almost completed the script with the fix.. Thanks a lot for helping me out.

**Comment by TandelK** [comment]
Fixed with today's update.
